defmodule AperDeskWeb.SitemapController do
  @moduledoc """
  The sitemap, generated from what is actually published.

  Written as a route rather than a file because the directory changes whenever
  a studio publishes or withdraws a listing, and a static file regenerated by
  hand is a file that is wrong most of the time. A sitemap listing a withdrawn
  studio teaches a crawler the site returns 404s.

  Only the pages that opt into indexing appear — the marketing site, the
  directory hub, its city pages and its published profiles. Nothing reached by
  a share token is here, for the reason spelled out in `AperDeskWeb.SEO`.
  """
  use AperDeskWeb, :controller

  alias AperDesk.Directory

  def index(conn, _params) do
    conn
    |> put_resp_content_type("application/xml")
    |> send_resp(200, build(conn))
  end

  defp build(conn) do
    entries =
      static_entries(conn) ++ city_entries(conn) ++ profile_entries(conn)

    """
    <?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    #{Enum.map_join(entries, "\n", &entry/1)}
    </urlset>
    """
  end

  # Priority is a hint the major engines largely ignore, so it is set by honest
  # relative importance rather than tuned: the city pages are what this site is
  # for, and the marketing page is what pays for it.
  defp static_entries(conn) do
    [
      %{loc: url(conn, ~p"/"), changefreq: "weekly", priority: "1.0"},
      %{loc: url(conn, ~p"/photographers"), changefreq: "daily", priority: "0.9"}
    ]
  end

  defp city_entries(conn) do
    Enum.map(Directory.list_cities(), fn city ->
      %{
        loc: url(conn, ~p"/photographers/#{Directory.city_slug(city.city)}"),
        changefreq: "daily",
        priority: "0.8"
      }
    end)
  end

  defp profile_entries(conn) do
    Directory.search(limit: 5_000)
    |> Enum.filter(& &1.city)
    |> Enum.map(fn listing ->
      %{
        loc:
          url(
            conn,
            ~p"/photographers/#{Directory.city_slug(listing.city)}/#{listing.studio.slug}"
          ),
        lastmod: listing.updated_at && DateTime.to_date(listing.updated_at),
        changefreq: "weekly",
        priority: "0.7"
      }
    end)
  end

  defp entry(%{loc: loc} = attrs) do
    [
      "  <url>",
      "    <loc>#{escape(loc)}</loc>",
      attrs[:lastmod] && "    <lastmod>#{attrs.lastmod}</lastmod>",
      "    <changefreq>#{attrs.changefreq}</changefreq>",
      "    <priority>#{attrs.priority}</priority>",
      "  </url>"
    ]
    |> Enum.reject(&is_nil/1)
    |> Enum.join("\n")
  end

  # A studio slug is generated, but a sitemap that is not well-formed XML is
  # discarded whole rather than partially — so escaping is not optional.
  defp escape(value) do
    value
    |> String.replace("&", "&amp;")
    |> String.replace("<", "&lt;")
    |> String.replace(">", "&gt;")
    |> String.replace("\"", "&quot;")
    |> String.replace("'", "&apos;")
  end
end
