defmodule AperDesk.Storage.Local do
  @moduledoc """
  Files on the local disk, served by the endpoint's static plug.

  For development and single-node deployments. It is deliberately dull: no
  processing, no derivatives, no CDN. The one thing it does take seriously is
  refusing to write outside its root — keys are generated by
  `AperDesk.Storage`, but an adapter that trusts its caller's path is one
  refactor away from being an arbitrary-write primitive.
  """
  @behaviour AperDesk.Storage

  alias AperDesk.Storage

  @impl true
  def put(key, source_path, _opts \\ []) do
    with {:ok, destination} <- resolve(key),
         :ok <- File.mkdir_p(Path.dirname(destination)),
         :ok <- copy(source_path, destination) do
      {:ok, key}
    end
  end

  @impl true
  def delete(key) do
    with {:ok, path} <- resolve(key) do
      case File.rm(path) do
        :ok -> :ok
        {:error, :enoent} -> :ok
        error -> error
      end
    end
  end

  @impl true
  def delete_prefix(prefix) do
    with {:ok, path} <- resolve(prefix) do
      File.rm_rf(path)
      :ok
    end
  end

  @impl true
  def fetch(key, dest_path) do
    with {:ok, source} <- resolve(key),
         :ok <- File.mkdir_p(Path.dirname(dest_path)),
         {:ok, _bytes} <- File.copy(source, dest_path) do
      {:ok, dest_path}
    else
      {:error, reason} -> {:error, reason}
    end
  end

  @impl true
  def url(key), do: Path.join(public_base_url(), key)

  # `File.cp/2` rather than `File.rename/2`: LiveView's temporary file may sit
  # on a different filesystem from the upload root, where a rename fails.
  defp copy(source, destination) do
    case File.cp(source, destination) do
      :ok -> :ok
      {:error, reason} -> {:error, reason}
    end
  end

  defp resolve(key) do
    root = Path.expand(root())
    candidate = Path.expand(Path.join(root, key))

    if candidate == root or String.starts_with?(candidate, root <> "/") do
      {:ok, candidate}
    else
      {:error, :outside_root}
    end
  end

  defp root, do: Keyword.get(Storage.config(), :root, "priv/static/uploads")

  defp public_base_url, do: Keyword.get(Storage.config(), :public_base_url, "/uploads")
end
